<?php

namespace App\Models\Models\apps;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Device extends Model
{
    use HasFactory;
    protected $table = 'devices';
    protected $guarded = [];

    public function DeviceGroup()
    {
        return $this->belongsTo(DeviceGroup::class, 'device_group_id');
    }

    public function Category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function Room()
    {
        return $this->belongsTo(Room::class, 'room_id');
    }

    public function DevicePrefix(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(DevicePrefix::class, 'device_prefix_id');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->number = Device::where('device_prefix_id', $model->device_prefix_id)->max('number') + 1;
            $model->full_number = $model->DevicePrefix->prefix . '-' . str_pad($model->number, 5, 0, STR_PAD_LEFT);
        });
    }
}
