<?php

namespace App\Models\Models\apps;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    use HasFactory;
    protected $table = 'documents';
    protected $fillable = [
        'number',
        'document_prefix_id',
        'full_number',
        'code',
        'qty',
        'status',
        'can_edit',
        'can_export',
        'is_export'
    ];

    public function DocumentInfo(){
        return $this->hasMany(DocumentInfo::class, 'document_id');
    }

    protected function DocumentPrefix(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(DocumentPrefix::class, 'document_prefix_id');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model){
            $model->number = Document::where('document_prefix_id', $model->document_prefix_id)->max('number') + 1;
            $model->full_number = $model->DocumentPrefix->prefix . '-' . str_pad($model->number, 5, 0, STR_PAD_LEFT);
        });
    }
}
