<?php

namespace App\Models\Models\apps;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Liquidate extends Model
{
    use HasFactory;
    protected $table = 'liquidates';
    protected $guarded = [];

    public function LiquidateInfo(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(LiquidateInfo::class, 'liquidate_id');
    }

    public function Document_prefix(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(DocumentPrefix::class, 'document_prefix_id');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model){
            $model->number = Liquidate::where('document_prefix_id', $model->document_prefix_id)->max('number') + 1;
            $model->full_number = $model->Document_prefix->prefix . '-' . str_pad($model->number, 5, 0, STR_PAD_LEFT);
        });
    }
}
